name: Build bottles

on: pull_request

env:
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jonchang/audit-action@master
  build-macos-bottles:
    runs-on: macos-latest
    steps:
      - name: Update Homebrew
        run: brew update-reset
      - uses: actions/checkout@master
      - name: Build bottles
        run: |
          mkdir -p "$(dirname $(brew --repo ${{github.repository}}))"
          cp -a "$GITHUB_WORKSPACE" "$(brew --repo ${{github.repository}})"
          "$(brew --repo kde-mac/kde)/tools/do-caveats.sh"
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --cleanup --root-url=https://dl.bintray.com/kde-mac/bottles-kde
          cp -a ~/bottles $RUNNER_TEMP/
      - name: Upload bottles
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: ${{runner.temp}}/bottles
